### ISSUE TITLE
Installation funktioniert nicht

### ISSUE THREAD

**Issue by Egahras** [wolfgang-wiedermann/php_mobile_accounting#12]
Habe lediglich unter einer Standard Xampp installation das Verzeichnis erstellt und die Dateien hineinkopiert. Installation schaut nicht so aus wie in dem Guide auf deiner Seite und funktioniert leider auch nicht. Eine Idee woran es liegen könnte?

![Image of Error](http://thinio.net/img/install-error.PNG)

**Comment by nesc58** [comment]
Gleicher Fehler ebenfalls bei mir mit der neusten Version. (Master)

**Comment by wolfgang-wiedermann** [comment]
Ist es möglich, dass in Ihrem Browser Javascript deaktiviert ist, oder dass beim Entpacken nicht alle Dateien im Zielverzeichnis gelandet sind?

**Comment by Egahras** [comment]
Javascript ist nicht deaktiviert. Mehrfach geprüft ob Alle dateien vorhanden sind.... Ja sind sie. Hatte bisher keinen Fehler gefunden...

**Comment by wolfgang-wiedermann** [comment]
ist die Installation aus der *.zip-Datei unter Releases oder einfach ein checkout des Master-Branchs?

**Comment by wolfgang-wiedermann** [comment]
wenns der Master-Branch ist bitte ich um einmal

git checkout 03d0ddd3d40430aa7700a20

und einen neuerlichen Test, denn das neue Release, das im Master steckt ist noch nicht fertig.
