### ISSUE TITLE
Allgemeine Fehler beim Starten (neue Installation)

### ISSUE THREAD

**Issue by nesc58** [wolfgang-wiedermann/php_mobile_accounting#13]
Hallo zusammen,
ich habe das System installiert. Tabelle wurde ordnungsgemäß erstellt.

Beim Starten hingegen erhalte ich folgenden Fehler:
![unbenannt](https://cloud.githubusercontent.com/assets/14092074/9714738/4744dd00-555a-11e5-8b23-72577e437516.PNG)

Es ist nicht nur der Fehler der auftritt, sondern ebenfalls kein Konto errichtet werden kann. Die Spalte "Kontoart" bleibt leer trotz der Eintragung in der Datenbank. Ich gehe davon aus, dass all dies folgefehler sind.
![unbenannt](https://cloud.githubusercontent.com/assets/14092074/9714857/68f87352-555b-11e5-9c4f-481164e6c015.PNG)

System:
Apache: 2.4
PHP-Version: 5.5.8
MySQL-Api: 5.0.11
MySQL-Server: 5.5.35-MariaDB
Protokoll-Version: 10
Zeichensatz: UTF-8 Unicode

Getestet mit Firefox v39 und Internet Explorer 11

Gruß,
Nesc

**Comment by wolfgang-wiedermann** [comment]
Hallo, 

das Problem dürfte hier sein, dass Ihr Apache2 die .htaccess-Datei nicht interpretiert. Bitte hier einfach mal in der Apache Konfiguration prüfen, ob an den entsprechenden Stellen in der /etc/apache2/apache2.conf für den Bereich Ihrer html5-haushaltsbuch-Installation AllowOverride All und  AccessFileName .htaccess gesetzt ist.

Viele Grüße

Wolfgang Wiedermann
