### ISSUE TITLE
Probleme mit SSL+JS nur(!) auf Apple-Geräten

### ISSUE THREAD

**Issue by mapdi** [wolfgang-wiedermann/php_mobile_accounting#15]
Ich habe das aktuelle HTML5-Haushaltsbuch (mit htaccess-Schutz) auf eine Synology NAS installiert. Funktiniert auch gut soweit auf Windows und Android-Geräten. Alleridngs kalppt der Zugriff per IOS (Iphone+Ipad) nicht. Die htaccess-Anmeldung wird nicht einmal akzeptiert bzw. angenommen. Ohne die .htaccess-Datei kommen lauter Fehlermeldungen, vermutlich JS-Fehler. Kann das an dem SSL-Zertifikat liegen oder eher an den JS-Komponenten?

**Comment by wolfgang-wiedermann** [comment]
Hallo,
ich nutze das aktuelle HTML5-Haushaltsbuch sehr häufig mit dem iPhone (aktuelles ios 9.x) da gibt es seit Jahren keine Probleme. Können Sie mir bitte den  in Ihrem NAS verwendenten Webserver (Apache2, nginx ...) und die genaue Fehlermeldung mitteilen. Den JS-Fehler kann ich jedenfalls sicher ausschließen.
Viele Grüße

**Comment by mapdi** [comment]
Hallo, Herr Wiedemann,

vielen Dank für Ihre Rückmeldung.

Auf dem NAS läuft:
PHP ==> 5.5 	
MySQL/MariaDB ==> 5.5 
Apache ==> 2.2 (Unix)

Mittlerweile habe ich das "Problem" behoben bzw. es umgangen. Offenbar lag die Ursache an der SSL-Verschlüsselung (https://...) des Servers. Das Zertifikat ich echt, ausgestellt vom COMODO. Die Version ohne SSL (Ihres HTML-5 Haushaltsbuchs) kann man Fehlerfrei auf dem iPhone (Apple-Geräten) ausführen.

Ggf. hilft Ihnen die Eingrenzung weiter?

Nochmals vielen Dank für Ihre Mühen und die Bereitstellung des Haushaltsbuchs für die Öffentlichkeit.

Viele Grüße,
mapdi

**Comment by wolfgang-wiedermann** [comment]
Hallo,

ich verwende Apache 2.4 mit einem Zertifikat von Startcom auf Debian bzw. Ubuntu, also ein ziemlich ähnliches Setup. Bei mir gibt es wie gesagt keine Probleme. Das Problem, das bei Ihnen auftritt kann ich mir leider nicht erklären. Aber es müsste eigentlich bei anderen Web-Anwendungen auf Ihrem NAS auch auftreten?

Viele Grüße

Wolfgang Wiedermann
