### ISSUE TITLE
Fehlermeldung: Fehler beim Laden der Kontenarten aufgetreten: 500 Internal Server Error

### ISSUE THREAD

**Issue by axwerner** [wolfgang-wiedermann/php_mobile_accounting#19]
Guten Tag,
vielleicht ist dieser Fehler schon einmal aufgetaucht. Ich habe ihn in den bestehenden Issues nicht finden können.
Ich habe eine QNAP mit aktualisiertem OS. Die PHP vom Haushaltsbuch habe ich in das Web-Verzeichnis geladen. Der Web Server funktioniert und wurde mit anderer PHP bereits benutzt.
Die Datenbank ist der QNAP SQL Server uf Port 3306. Die Installation lief gut, die Datenbankstruktur mit Inhalt wurde angelegt.
Sobald ich jedoch die Webseite des Haushaltsbuchs aufrufe, bekomme ich die Fehlermeldung für die verschiedenen Felder der DB. Habe ich alle OK gecklickt, dann erscheint die Webseite, aber ohne Funktion.

Vielen Dank im Vorraus für Ihre Unterstützung,
Gruß Axel

**Comment by axwerner** [comment]
Hallo Wolfgang,

 

die Authentifizierung scheint zu funktionieren.

Ich werde nach Benutzernamen und Passwort gefragt und nur bei der richtigen Kombination geht es weiter zum Fehler 500.

Ich werde versuchen mich mit SSH an der NAS anzumelden und die Module zu laden.

 

Schöne Grüße,

Axel

 

Von: Wolfgang Wiedermann [mailto:notifications@github.com] 
Gesendet: Dienstag, 22. Januar 2019 08:02
An: wolfgang-wiedermann/php_mobile_accounting <php_mobile_accounting@noreply.github.com>
Cc: axwerner <axel_we@yahoo.de>; Author <author@noreply.github.com>
Betreff: Re: [wolfgang-wiedermann/php_mobile_accounting] Fehlermeldung: Fehler beim Laden der Kontenarten aufgetreten: 500 Internal Server Error (#19)

 

Hallo Axel,

das klingt so als würde die Authentifizierung nicht durchgeführt oder dem System ist der aktuell über den Browser angemeldete Benutzer nicht bekannt. Deshalb meine Frage: Kommt beim Öffnen der Seite ein Anmeldedialog für die Basic-Authentication?

Sind die entsprechenden Apache-Module für Basic-Authentication vorhanden?
(vgl. https://www.qnap.com/de-de/how-to/faq/article/wie-lade-ich-apache-webserver-module-manuell-auf-ein-nas/)

Viele Grüße

Wolfgang

**Comment by axwerner** [comment]
Ich habe die vier Module geladen; sie tauchen in dem Verzeichnis /usr/local/apache/modules auf. Nach dem Zeitstempel der Dateien waren sie jedoch schon vorher da.

Dias Verhalten ist leider dasselbe.

 

Schöne Grüße,

Axel

 

Von: axel_we [mailto:axel_we@yahoo.de] 
Gesendet: Donnerstag, 24. Januar 2019 19:01
An: 'wolfgang-wiedermann/php_mobile_accounting' <reply@reply.github.com>; 'wolfgang-wiedermann/php_mobile_accounting' <php_mobile_accounting@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Betreff: AW: [wolfgang-wiedermann/php_mobile_accounting] Fehlermeldung: Fehler beim Laden der Kontenarten aufgetreten: 500 Internal Server Error (#19)

 

Hallo Wolfgang,

 

die Authentifizierung scheint zu funktionieren.

Ich werde nach Benutzernamen und Passwort gefragt und nur bei der richtigen Kombination geht es weiter zum Fehler 500.

Ich werde versuchen mich mit SSH an der NAS anzumelden und die Module zu laden.

 

Schöne Grüße,

Axel

 

Von: Wolfgang Wiedermann [mailto:notifications@github.com] 
Gesendet: Dienstag, 22. Januar 2019 08:02
An: wolfgang-wiedermann/php_mobile_accounting <php_mobile_accounting@noreply.github.com <mailto:php_mobile_accounting@noreply.github.com> >
Cc: axwerner <axel_we@yahoo.de <mailto:axel_we@yahoo.de> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [wolfgang-wiedermann/php_mobile_accounting] Fehlermeldung: Fehler beim Laden der Kontenarten aufgetreten: 500 Internal Server Error (#19)

 

Hallo Axel,

das klingt so als würde die Authentifizierung nicht durchgeführt oder dem System ist der aktuell über den Browser angemeldete Benutzer nicht bekannt. Deshalb meine Frage: Kommt beim Öffnen der Seite ein Anmeldedialog für die Basic-Authentication?

Sind die entsprechenden Apache-Module für Basic-Authentication vorhanden?
(vgl. https://www.qnap.com/de-de/how-to/faq/article/wie-lade-ich-apache-webserver-module-manuell-auf-ein-nas/)

Viele Grüße

Wolfgang

**Comment by wolfgang-wiedermann** [comment]
Bitte mal in den Ordner html/ eine Datei info.php mit folgendem Inhalt legen

<?php phpinfo(); ?>

und diese Datei über den Browser aufrufen. Mich würde die Rubrik mit den Umgebungsvariablen interessieren.

**Comment by axwerner** [comment]
Hallo Wolfgang,

 

habe die PDF angehängt.

 

Gruß

Axel

 

Von: Wolfgang Wiedermann [mailto:notifications@github.com] 
Gesendet: Montag, 28. Januar 2019 16:54
An: wolfgang-wiedermann/php_mobile_accounting <php_mobile_accounting@noreply.github.com>
Cc: axwerner <axel_we@yahoo.de>; Author <author@noreply.github.com>
Betreff: Re: [wolfgang-wiedermann/php_mobile_accounting] Fehlermeldung: Fehler beim Laden der Kontenarten aufgetreten: 500 Internal Server Error (#19)

 

Bitte mal in den Ordner html/ eine Datei info.php mit folgendem Inhalt legen

und diese Datei über den Browser aufrufen. Mich würde die Rubrik mit den Umgebungsvariablen interessieren.

**Comment by wolfgang-wiedermann** [comment]
Hallo Axel,

leider habe ich kein PDF erhalten.

Viele Grüße

Wolfgang
