### ISSUE TITLE
Chrome Kompatibilität

### ISSUE THREAD

**Issue by martin-dr** [wolfgang-wiedermann/php_mobile_accounting#21]
Seit Chrome 85 ist der hier verwendete AppCache per Default deaktiviert. Über das hier

https://web.dev/appcache-removal/

beschriebene Vorgehen kann man die Anwendung wieder lauffähig bekommen. Das geht aber nur noch bis zum 21.10.2021. Danach stirbt die Funktion ganz und das Haushaltsbuch ist nicht mehr per Chrome zu bedienen.

Wäre es möglich, den AppCache aus der Anwendung zu entfernen?

**Comment by wolfgang-wiedermann** [comment]
Danke für den Hinweis, ich versuche das zeitnah in Form eines neuen Releases bereitzustellen. Wird sowieso Zeit der Software mal wieder etwas Pflege zukommen zu lassen.

P. S. ist mir bisher nicht aufgefallen, da ich die Anwendung selbst die letzten Jahre immer via Firefox benutzt habe.

**Comment by wolfgang-wiedermann** [comment]
sollte mit https://github.com/wolfgang-wiedermann/php_mobile_accounting/commit/c15cf02fd69aa8bf6d2bc39bd483d01011066cd2 behoben sein. Die Version funktioniert übrigens auch sauber mit PHP 8

**Comment by wolfgang-wiedermann** [comment]
Mit https://github.com/wolfgang-wiedermann/php_mobile_accounting/releases/tag/v0.3.0 gibt es jetzt auch ein offizielles Release, dass die Änderungen enthält.
